export const ADD_PIZZA_TO_CART = 'ADD_PIZZA_TO_CART'
export const REMOVE_PIZZA_FROM_CART = 'REMOVE_PIZZA_FROM_CART'
export const CALC_TOTAL = 'CALC_TOTAL'

export const CHANGE_CURRENCY = 'CHANGE_CURRENCY'
